config/routes.rb
Draftful::Application.routes.draw do

  resources :drafts

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  attr_accessible :order

  belongs_to :player
  belongs_to :draft
end

app/models/commissioner.rb
class Commissioner < ActiveRecord::Base
  attr_accessible :current_pick, :pick_time_limit, :start_time

  belongs_to :draft
  has_one :selection
end

app/models/declaration.rb
class Declaration < ActiveRecord::Base
  attr_accessible :rank

  belongs_to :draft
  belongs_to :item

end

app/models/draft.rb
class Draft < ActiveRecord::Base
  has_secure_password
  attr_accessible :is_private, :is_snake, :password, :password_confirmation


  has_one :room
  has_one :commissioner
  has_many :declarations
  has_many :items, through: :declarations, as: :available
  has_many :assignments
  has_many :players, through: :assignments

  def self.private_drafts
	Draft.where("is_private = ?", true)
  end

  def self.public_drafts
	Draft.where("is_private = ?", false)
  end

  def is_private?
	self.is_private
  end

  def is_public?
	!is_private?
  end

  def is_snake?
	self.is_snake
  end

  def is_linear?
	!is_snake?
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :name

  has_one :declaration
  has_one :draft, through: :declaration
  has_one :selection
  has_one :player, through: :selection
end

app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible :maximum_occupancy, :minimum_occupancy, :name, :url

  belongs_to :draft
end

app/models/selection.rb
class Selection < ActiveRecord::Base
  attr_accessible :order

  belongs_to :commissioner
  belongs_to :item
  belongs_to :player
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
  def index
    @drafts = Draft.public_drafts
  end

	def new
	  @draft = Draft.new
	end

  def create
    @draft = Draft.new(params[:draft])
    @commissioner = Commissioner.new(params[:commissioner])
    @room = Room.new(params[:room])

    if @draft.valid? and @commissioner.valid? and @room.valid?
      @draft = Draft.create(params[:draft])
      @draft.create_commissioner(params[:commissioner])
      @draft.create_room(params[:room])
      
      flash[:success] = "Your draft was saved!"
      redirect_to drafts_path
    else
      flash[:error] = "Your draft could not be saved"
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drafts_helper.rb
module DraftsHelper
end

app/views/drafts/_form.html.erb
<% options ||= {} %>

<%= form_for(draft, options) do |builder| %>
  <fieldset>
    <legend>Draft</legend>
    <%= fields_for draft.build_room do |room_builder| %>
      <%= room_builder.label :name, "Draft Name" %>
      <%= room_builder.text_field :name %>

      <%= room_builder.label :minimum_occupancy %>
      <%= room_builder.number_field :minimum_occupancy, min: 0 %>

      <%= room_builder.label :maximum_occupancy %>
      <%= room_builder.number_field :maximum_occupancy, min: 0 %>
    <% end %>
  </fieldset>

  <fieldset>
    <legend>Timing</legend>
    <%= fields_for draft.build_commissioner do |commissioner_builder| %>
      <%= commissioner_builder.label :start_time %>
      <%= commissioner_builder.datetime_select :start_time %>

      <%= commissioner_builder.label :pick_time_limit%>
      <%= commissioner_builder.time_select :pick_time_limit %>
    <% end %>
  </fieldset>

  <fieldset>
    <legend>Options</legend>
    <%= builder.label :is_snake, "Draft Type" %>
    <%= builder.select :is_snake, [["Snake", true], ["Linear", false]] %>

    <%= builder.label :is_private, "Privacy" %>
    <%= builder.select :is_private, [["Public", false], ["Password protected", true]] %>

    <%= builder.label :password %>
    <%= builder.password_field :password %>

    <%= builder.label :password_confirmation %>
    <%= builder.password_field :password_confirmation %>

  </fieldset>

  <%= builder.submit "Create!", class: "button expand" %>

<% end %>

app/views/drafts/index.html.erb
<ul>
  <%= @drafts.each do |draft| %>
    <%= link_to draft.name, draft_path(draft) %>
  <% end %>
</ul>
<%= link_to "New Draft", new_draft_path %>

app/views/drafts/new.html.erb
<div class="row">
  <div class="large-6 large-centered columns">
    <%= render partial: 'form', locals: {draft: @draft} %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>